version: '3.5'
services:
  phpmad_pull_request_server:
    image: mgonzalezbaile/php_base:1.0
    container_name: phpmad_pull_request_server
    volumes:
      - ..:/opt/project
    working_dir: /opt/project/PullRequest
    ports:
      - "8080:8080"
    command: '/opt/project/PullRequest/bin/console server:run 0.0.0.0:8080'
    networks:
      - phpmad-codereview-network

networks:
  phpmad-codereview-network:
    external: true
